apiVersion: v1
kind: Secret
metadata:
  name: techseminar2-secret
  namespace: channel
type: Opaque
stringData:
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: mydlcodb2004!
  PGVECTOR_USERNAME: postgres
  PGVECTOR_PASSWORD: postgres
